### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sulincix** [pardus/pardus-lightdm-greeter#8]
- [x] check user search box functions
- [x] user selection button improvements
- [x] default wallpaper detection improvements
